// Embeds templates/client-repo/** into a TS module so the setup PR works in a serverless bundle.
// Run: pnpm templates  (also runs before build). A test checks the output is up to date.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = join(process.cwd(), "templates/client-repo");
const out = join(process.cwd(), "src/integrations/github/templates.generated.ts");

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

export function renderTemplatesModule(): string {
  const files = walk(root)
    .sort()
    .map((p) => ({ path: relative(root, p).split("\\").join("/"), content: readFileSync(p, "utf8") }));
  return `// Generated by scripts/embed-templates.ts from templates/client-repo. Do not edit.\nexport const CLIENT_REPO_TEMPLATES: { path: string; content: string }[] = ${JSON.stringify(files, null, 2)};\n`;
}

if (process.argv[1]?.endsWith("embed-templates.ts")) {
  writeFileSync(out, renderTemplatesModule());
  console.log(`Wrote ${relative(process.cwd(), out)}`);
}
